# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-23 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload-file', 'Submission')], default='upload-file', max_length=20, verbose_name='action')),
                ('message', models.CharField(default='nothing', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
            ],
            options={
                'verbose_name': 'Action log',
                'verbose_name_plural': 'Actions log',
            },
        ),
    ]
