# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-23 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exstore', '0002_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Log', 'verbose_name_plural': 'Logs'},
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('file_upload', 'file_upload')], default='file_upload', max_length=20, verbose_name='action'),
        ),
    ]
