web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8089:8000"
  links:
    - db
db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=composetest
    - MYSQL_PASSWORD=testpassword
    - MYSQL_DATABASE=composetest
